export const CLIENT_ID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;
export const CLIENT_SECRET = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_SECRET;
export const NEXTAUTH_SECRET = process.env.NEXT_PUBLIC_NEXTAUTH_SECRET
export const FACEBOOK_CLIENT_ID = process.env.NEXT_PUBLIC_FACEBOOK_CLIENT_ID
export const FACEBOOK_CLIENT_SECRET = process.env.NEXT_PUBLIC_FACEBOOK_CLIENT_SECRET